apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-jupyter-on-k8s-04
spec:
  portal:
    sessions:
      maximum: 3
  workshops:
  - name: lab-jupyter-on-k8s-04
    expires: 45m
    orphaned: 5m
