apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-04
spec:
  title: "Jupyter on Kubernetes #4"
  description: A workshop exploring use of Carvel tools to deploy Jupyter notebooks to Kubernetes.
  url: https://github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-04
  content:
    files: github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-04
  duration: 45m
  session:
    namespaces:
      budget: large
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
