#@ load("@ytt:data", "data")
#@ load("@ytt:sha256", "sha256")

#@ load("setup-environment.lib.txt", "startup_script")

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.name
  labels:
    app: #@ data.values.name
type: Opaque
stringData:
  "setup-environment.sh": #@ startup_script()
